baseurl = "https://vinay-keshava.gitlab.io/" # Hostname (and path) to the root.
title = "Vinay Keshava" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "Vinay" # Enable or disable Disqus.

[params] # theme parameters
    author = "Vinay Keshava" # Author's name.
    info = "FOSS Enthusiast" # Author's job title or info.
    description = "Vinay Keshava's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/vinay.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Enter a text here." # Add footer content
    fixedbarContent = "Do you want to know me more private?→" # Add fixedbar content
    fixedbarContentAfter = "Thank You! Please share it if you like it→" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    enableLinkedInShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
#    enableTwitterShare = true  # new add
 #   enableFacebookShare = true # new add
#    enableHatenaShare = true   # new add
 #   enableLineShare = true     # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/vinay-keshava/"
[[params.social]]
    name = "Matrix"
    #icon = "fab fa-twitter"
    weight = 3
    url = "https://matrix.to/#/@vinay-keshava:matrix.org)"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/vinay-keshava/"
#[[params.social]]
#    If icon is not set, Text is displayed.
#    name = "LinkedIn"
#    weight = 6
#    url = "https://www.linkedin.com/in/naro143/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url = "https://vinay-keshava.github.io"
[[menu.main]]
    name="Projects"
    weight=2
    url="projects"
[[menu.main]]
    name="Contact Me"
    weight=3
    url="contact"
